use_frameworks!

target 'Pecan_Example' do
  pod 'Pecan',      :path => '../Pecan.podspec'
#  pod 'TestModule', :path => '../TestModule.podspec'
  
end


module Pod
  class PodTarget
    def static_framework?
      return true
    end
  end
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "YYCache"
      target.build_configurations.each do |config|
        config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = "YES"
      end
    end
  end
end
